export default {
  justNow: '지금',
  secondsAgo: '{{time}}초 전',
  aMinuteAgo: '1분 전',
  minutesAgo: '{{time}}분 전',
  anHourAgo: '한시간 전',
  hoursAgo: '{{time}}시간 전',
  aDayAgo: '어제',
  daysAgo: '{{time}}일 전',
  aWeekAgo: '1주 전',
  weeksAgo: '{{time}}주 전',
  aMonthAgo: '한달 전',
  monthsAgo: '{{time}}달 전',
  aYearAgo: '1년 전',
  yearsAgo: '{{time}}년 전',
  overAYearAgo: '몇 년 전',
  secondsFromNow: '{{time}}초 후',
  aMinuteFromNow: '1분 후',
  minutesFromNow: '{{time}}분 후',
  anHourFromNow: '한시간 후',
  hoursFromNow: '{{time}}시간 후',
  aDayFromNow: '내일',
  daysFromNow: '{{time}}일 후',
  aWeekFromNow: '일주일 후',
  weeksFromNow: '{{time}}주 후',
  aMonthFromNow: '한달 후',
  monthsFromNow: '{{time}}달 후',
  aYearFromNow: '일년 후',
  yearsFromNow: '{{time}}년 후',
  overAYearFromNow: '1년 이상'
};
